USE [master]
GO

/****** Object:  Database [CrudOperation]    Script Date: 4/5/2021 12:23:42 PM ******/
CREATE DATABASE [CrudOperation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CrudOperation', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CrudOperation.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CrudOperation_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CrudOperation_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CrudOperation] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CrudOperation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CrudOperation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CrudOperation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CrudOperation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CrudOperation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CrudOperation] SET ARITHABORT OFF 
GO

ALTER DATABASE [CrudOperation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CrudOperation] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CrudOperation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CrudOperation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CrudOperation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CrudOperation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CrudOperation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CrudOperation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CrudOperation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CrudOperation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CrudOperation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CrudOperation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CrudOperation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CrudOperation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CrudOperation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CrudOperation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CrudOperation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CrudOperation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CrudOperation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CrudOperation] SET  MULTI_USER 
GO

ALTER DATABASE [CrudOperation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CrudOperation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CrudOperation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CrudOperation] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CrudOperation] SET  READ_WRITE 
GO


